### ISSUE TITLE
A question about the training

### ISSUE THREAD

**Issue by xinchenduobian** [VITA-Group/EnlightenGAN#100]
May I ask which directory the training data set is placed in? There are only detailed steps about the test script in the readme. Thank you very much

**Comment by yueruchen** [comment]
`../final_dataset/trainA` and `../final_dataset/trainB`

**Comment by xinchenduobian** [comment]
Thank you very much, but when I run the training script and run the command: python scripts/script.py --train, the following problems still occur. I tried to delete all the files in the _pycache_ folder, but it didn't work.
![截图_2021-08-23_11-20-11](https://user-images.githubusercontent.com/60869601/130386184-909075ef-cc65-4e0d-b138-26130b4a9a26.png)

**Comment by yueruchen** [comment]
It seems to be a bug with yaml. I guess you can simply delete it as yaml is actually not used

**Comment by xinchenduobian** [comment]
Yes, just comment out the training script: #config = get_config(opt.config). Thank you very much.
