### ISSUE TITLE
What is dataset_mode ??

### ISSUE THREAD

**Issue by edwardcho** [VITA-Group/EnlightenGAN#101]
Hello Sir.

I saw dataset_mode in your code (data/custom_dataset_data_loader.py).
What is dataset_mode??

According to dataset_mode, what should I check for training using my-datasets ?
(Actually, I only have low-light images)

Thanks.
Edward Cho.

**Comment by yueruchen** [comment]
You can not train it if you only have low-light images

**Comment by edwardcho** [comment]
Hello yueruchen.

I think that ElightenGAN is unsupervised learning type for image enhancement.
So I think that this network needs only low-light images for training.

If not, what should I prepare training?
(If so, this network is not type of unsupervised learning ?)

Thanks,
Edward Cho.

**Comment by yueruchen** [comment]
This is unsupervised learning, but no PAIRED training data. Which means you don't need to provide a normal light ground truth for low-light input images. So you should prepare both the low-light and normal light image examples, but they don't need to be the same scene.
