### ISSUE TITLE
what does this code means? times = random.randint(self.low_times,self.high_times)/100.

### ISSUE THREAD

**Issue by asdawnasd** [VITA-Group/EnlightenGAN#102]
Dear sir/madam, 
I am confused about the code in unaligned_dataset.py, line 120, 
`times = random.randint(self.opt.low_times,self.opt.high_times)/100.`
what does it mean? Why should the `input_img`  be devide by `times`?
Appreaciate for your relpy!!

**Comment by yueruchen** [comment]
It is for random brightness augmentation

**Comment by asdawnasd** [comment]
Oh! I see. Thank you！！
