### ISSUE TITLE
exchange trainA and trainB

### ISSUE THREAD

**Issue by aimen123** [VITA-Group/EnlightenGAN#122]
I want to exchange trainA and trainB, can we achieve the effect of darkening? Can the code be completed?
thanks!

**Comment by yueruchen** [comment]
I dont try this before but you can definitely try and see hot it performs, by just exchanging the dataset

**Comment by aimen123** [comment]
I try it and fail. It dont work out very well

**Comment by yueruchen** [comment]
maybe you could upload some results here

**Comment by aimen123** [comment]
loss does not converge，so....

**Comment by yueruchen** [comment]
I think loss will never converge, since it is an adversarial training. Usually I only look at the visual results

**Comment by wzr1201** [comment]
hi,have you successfully achieved the effect of darkening?
