### ISSUE TITLE
Code for calculate NIQE

### ISSUE THREAD

**Issue by KushinaYu** [VITA-Group/EnlightenGAN#124]
Can you provide the code for calculating the NIQE？ I have tested the NIQE by the code in https://github.com/guptapraful/niqe， but the NIQE results exceeded 10 in DICM/VV datasets which were completely different from the results in your paper.

**Comment by yueruchen** [comment]
https://github.com/VITA-Group/EnlightenGAN/issues/70#issuecomment-713321681

**Comment by LIXINJJ** [comment]
您好，我运行了模型，但是不知道评价指标如何体现出来，请问一下评价指标是将测试完成的图片，单独用代码测试出来的吗？还是将NIQE的评价指标代码加到模型里面。麻烦您解答一下。
