### ISSUE TITLE
train issues

### ISSUE THREAD

**Issue by Fancy-a-good-name** [VITA-Group/EnlightenGAN#132]
I had a problem and would like a friend to point me out。
train.py: error: the following arguments are required: --dataroot。
And My parameters are set as follows： self.parser.add_argument('--dataroot', type=str, default='/final_dataset', required=True, help='path to images (should have subfolders trainA, trainB, valA, valB, etc)')。

**Comment by fengyunyang** [comment]
I have meet the same problem. Whether you have solved the problem? If you solved, could you please tell the method.

**Comment by yifanjiang19** [comment]
I guess you should change `default='/final_dataset'` to `default='./final_dataset'` and change `required=True` to `required=False`
