### ISSUE TITLE
where to place the final_dataset folder?

### ISSUE THREAD

**Issue by phaniparsa** [VITA-Group/EnlightenGAN#133]
Hi All,

I am trying to run the model training code but ending up getting the below error:
AssertionError: ../final_dataset\trainA is not a valid directory

Could someone please help on where should the final_dataset folder be placed? I can see that a relative path is being used and I tried placing the final_dataset/trainA under the master folder, data folder and even the datasets folder but still getting the error.

Could someone please help me in resolving this issue?

**Comment by yifanjiang19** [comment]
As I specified in the readme, it should be placed on `../`
