### ISSUE TITLE
Questions about training data sets

### ISSUE THREAD

**Issue by hy9874** [VITA-Group/EnlightenGAN#143]
Unfortunately, the Google Cloud and Baidu Cloud links for the dataset are no longer available。
If anyone can give me a link or URL, I would be very grateful

**Comment by yifanjiang19** [comment]
updated google drive

**Comment by hy9874** [comment]
thank you very much




余琦
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VITA-Group/EnlightenGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月25日(星期四) 下午3:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VITA-Group/EnlightenGAN] Questions about training data sets (Issue #143)





 
Closed #143 as completed.
