### ISSUE TITLE
Predicting only use one gpu

### ISSUE THREAD

**Issue by ZYzhouya** [VITA-Group/EnlightenGAN#65]
Thanks for your great work!

When predicting, I found always only 1 gpu used, but actually I set 2 gpus to use. So I can't predict the results with 2 gpus and batchsize=1?

Waiting for your reply...

**Comment by yueruchen** [comment]
Yes, you can only use 1 gpu to predict.

**Comment by pengyaru** [comment]
> 
> 
> Yes, you can only use 1 gpu to predict.

你好，我想要./checkpoints/enlightening里面需要的预训练模型，但是谷歌网址https://drive.google.com/file/d/1AkV-n2MdyfuZTFvcon8Z4leyVb0i7x63/view我进入不了，所以请问您能给我一个百度云盘的链接吗？

**Comment by wx051** [comment]
Thanks for your work!
When downloading the pre-trained model, only the model of  200_net_G_A.pth is provided, and the 200_net_G_B.pth is missing. So I can't predict the results. Can you provide the the 200_net_G_B.pth. Thank you!
Looking forward to your reply.

**Comment by xuhui1994** [comment]
> Thanks for your great work!
> 
> When predicting, I found always only 1 gpu used, but actually I set 2 gpus to use. �So I can't predict the results with 2 gpus and batchsize=1?
> 
> Waiting for your reply...

你好，我总共两块显卡进行inference，但是使用nvidia-smi发现一张都没用到，你能给出加入gpu的代码吗，谢谢了

**Comment by yueruchen** [comment]
> Thanks for your work!
> When downloading the pre-trained model, only the model of 200_net_G_A.pth is provided, and the 200_net_G_B.pth is missing. So I can't predict the results. Can you provide the the 200_net_G_B.pth. Thank you!
> Looking forward to your reply.

You only need model A to get the results.

**Comment by yueruchen** [comment]
> > Thanks for your great work!
> > When predicting, I found always only 1 gpu used, but actually I set 2 gpus to use. �So I can't predict the results with 2 gpus and batchsize=1?
> > Waiting for your reply...
> 
> 你好，我总共两块显卡进行inference，但是使用nvidia-smi发现一张都没用到，你能给出加入gpu的代码吗，谢谢了

Could you please try to add `CUDA_VISIBLE_DEVICES=0` before your running command?

**Comment by yueruchen** [comment]
> > Yes, you can only use 1 gpu to predict.
> 
> 你好，我想要./checkpoints/enlightening里面需要的预训练模型，但是谷歌网址[https://drive.google.com/file/d/1AkV-n2MdyfuZTFvcon8Z4leyVb0i7x63/view我进入不了，所以请问您能给我一个百度云盘的链接吗？](https://drive.google.com/file/d/1AkV-n2MdyfuZTFvcon8Z4leyVb0i7x63/view%E6%88%91%E8%BF%9B%E5%85%A5%E4%B8%8D%E4%BA%86%EF%BC%8C%E6%89%80%E4%BB%A5%E8%AF%B7%E9%97%AE%E6%82%A8%E8%83%BD%E7%BB%99%E6%88%91%E4%B8%80%E4%B8%AA%E7%99%BE%E5%BA%A6%E4%BA%91%E7%9B%98%E7%9A%84%E9%93%BE%E6%8E%A5%E5%90%97%EF%BC%9F)

You can refer to this link: https://github.com/TAMU-VITA/EnlightenGAN/issues/28

**Comment by xuhui1994** [comment]
> > > Thanks for your great work!
> > > When predicting, I found always only 1 gpu used, but actually I set 2 gpus to use. �So I can't predict the results with 2 gpus and batchsize=1?
> > > Waiting for your reply...
> > 
> > 
> > 你好，我总共两块显卡进行inference，但是使用nvidia-smi发现一张都没用到，你能给出加入gpu的代码吗，谢谢了
> 
> Could you please try to add `CUDA_VISIBLE_DEVICES=0` before your running command?

I tried to do it ,it didnt work and encounterred a mistake. I want to know could the code be fixed in order to use more than one gpu in the predict phase. Looking forward your reply !

**Comment by AselSiriwardena** [comment]
Thanks for your work!
Can I know if I can train this model in a 1660ti 6b laptop?

**Comment by yueruchen** [comment]
@xuhui1994 You can change the testing code to dataparallel way following the training code

**Comment by yueruchen** [comment]
@AselSiriwardena One gpu can not store 32 batchsize, so it is not guaranteed to reproduce the results
