### ISSUE TITLE
Using Unet-256 as generator

### ISSUE THREAD

**Issue by Mayur28** [VITA-Group/EnlightenGAN#66]
Hi,

I've tried using 'unet_256' as the generator (specifying this in the script.py file), however, this has raised many errors. Thus far I've managed to adjust the code to get it to work but there are a few things that I was hoping to clarify.

1) In 'UnetSkipConnectionBlock', I see that ConvTranspose2D is being used and the empirical results reveal that a checkerboard effect is evident. To mitigate this, I've been trying to using bilinear upsampling instead but I'm currently encountering numerous issues trying to get the tensors to be the correct. If you could provide any guidance on how to go about using bilinear upsampling using the 'UnetGenerator', it would be highly appreciated.

2) I see that a 'unet_512' is available and would consequently would be trained on 512x512 images. In addition,  I see that the images in the dataset are 600x400 - I just wanted to find out is it recommended to resize the training images to 512x512 and thereafter train the model without negatively impacting the quality of the results?

Any assistance will be highly appreciated.

**Comment by yueruchen** [comment]
I'm not sure about other model's performance. I suggest you use the default model using in our paper.
