### ISSUE TITLE
Can this code apply to real-time video processing

### ISSUE THREAD

**Issue by xuhui1994** [VITA-Group/EnlightenGAN#68]
Thank you for your great work，I run your code and its very useful to images. And I want to know Can this code apply to real-time video processing !! I am urge to receive your reply.

**Comment by yueruchen** [comment]
I think you can run it on low-resolution videos

**Comment by xuhui1994** [comment]
I use the video which size is 1280x720, In the test phase , it appears that it can only use 1 **batchsize** and 1 **thre**ad.
so it may cost a lot of  time . I wanna to know can these setting (e.g. **batchsize** and **thread** in test phase) be changed    ? It can speed test ! Thanks a lot !

**Comment by xuhui1994** [comment]
And I set **gpu_ids  1,2** in test phase. But I find these no gpus works？I have 4 gpus totals
