### ISSUE TITLE
200_net_G_B.pth

### ISSUE THREAD

**Issue by wx051** [VITA-Group/EnlightenGAN#69]
你好，您提供的测试模型中，缺少200_net_G_B.pth，方便提供该文件吗？

**Comment by yueruchen** [comment]
模型都提供了，你需要check一下是否按照readme运行

**Comment by wx051** [comment]
你好，感谢回复。另请问在测试时，“model”应该设置为哪一个？我将其设置为“test”，增强结果效果很差。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yifan Jiang"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 下午2:10
收件人: "VITA-Group/EnlightenGAN"<EnlightenGAN@noreply.github.com&gt;; 
抄送: "学生伍旭"<995938447@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [VITA-Group/EnlightenGAN] 200_net_G_B.pth (#69)





 
模型都提供了，你需要check一下是否按照readme运行

**Comment by wx051** [comment]
你好，请问测试时，“which_model_netG”超参数应设置为哪一个？提供的代码设置的是“unet_256”，但是利用你们提供的模型测试时，提示有些参数是没有的，如下图。
我试过了其他几个“resnet_9blocks、resnet_6blocks...”等，也是提示缺少系列参数。
祝好，盼复！
伍旭







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VITA-Group/EnlightenGAN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 下午2:10
收件人:&nbsp;"VITA-Group/EnlightenGAN"<EnlightenGAN@noreply.github.com&gt;;
抄送:&nbsp;"学生伍旭"<995938447@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [VITA-Group/EnlightenGAN] 200_net_G_B.pth (#69)





 
模型都提供了，你需要check一下是否按照readme运行

**Comment by yueruchen** [comment]
在readme中都写了
```python scripts/script.py --predict```

**Comment by wx051** [comment]
感谢回复。
我目前是按照readme里面的测试教程来配置的。
-1 模型参数（200_net_G_A.pth）和网络（cycle_gan，默认的）所需参数不匹配（如下图），已经排除是单/多个GPU测试的问题。
-2 推测是选择的网络结构类型出问题。主要做出一下改动测试成功，但是效果不佳。
&nbsp; &nbsp; &nbsp;-1）将“model”设置为“test”（默认为“cycle_gan”），“dataset_mode”设置为“single”(默认为“unaligned”)
&nbsp; &nbsp; &nbsp;-2）将“which_model_netG”设置为“sid_unet_resize”（默认为“unet_256”）
祝好，盼复
伍旭







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yifan Jiang"<notifications@github.com&gt;; 
发送时间: 2020年10月24日(星期六) 上午8:21
收件人: "VITA-Group/EnlightenGAN"<EnlightenGAN@noreply.github.com&gt;; 
抄送: "学生伍旭"<995938447@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [VITA-Group/EnlightenGAN] 200_net_G_B.pth (#69)





 
在readme中都写了
 python scripts/script.py --predict
