### ISSUE TITLE
Can you release your code of calculating the value of NIQE?

### ISSUE THREAD

**Issue by JiaZhangbiubiu** [VITA-Group/EnlightenGAN#70]
I have trained and tested your code ,but I don't find the code of calculating the value of NIQE? Can you release your code of calculating the value of NIQE?

**Comment by yueruchen** [comment]
You can refer to this page https://live.ece.utexas.edu/research/Quality/index_algorithms.htm
http://live.ece.utexas.edu/research/Quality/niqe_release.zip

**Comment by yueruchen** [comment]
I use EXACTLY same matlab (matlab 2017 as platform) code as NIQE's author. What's the score of NIQE you got? Also, some of my friends from NTU and other following work (such as https://arxiv.org/pdf/2001.06826.pdf) can also reproduce NIQE score based on the released checkpoint. I think there should not have bug here.
