### ISSUE TITLE
Where are the tested images stored?

### ISSUE THREAD

**Issue by H-Li24** [VITA-Group/EnlightenGAN#76]
Hi.

I run the testing code successfully, but I cannot find where the tested/enhanced images are stored so I cannot compare them for my research.
Could you please help me with this problem?

![2020-12-25 22-57-01屏幕截图](https://user-images.githubusercontent.com/42953495/103136536-8f9ffc00-4704-11eb-9704-6f371f1adde0.png)

**Comment by HollyLee2000** [comment]
I can't find too! Wait for an answer lol.

**Comment by HollyLee2000** [comment]
I found them. As for me they're in EnlightenGAN-master\ablation\enlightening\test_200

**Comment by yueruchen** [comment]
Thank @HollyLee2000's explanation.
