### ISSUE TITLE
AssertionError: ../test_dataset\testA is not a valid directory

### ISSUE THREAD

**Issue by wu18078561329** [VITA-Group/EnlightenGAN#81]
How can I deal with the above problems?

**Comment by ComingPeopleHW** [comment]
> How can I deal with the above problems?

you haven't make a directory correctly.

**Comment by nikv97** [comment]
> How can I deal with the above problems?

Facinf wit hsame issue

**Comment by yueruchen** [comment]
@nikv97 you need to firstly create the directory
