### ISSUE TITLE
opt.patchD_3?

### ISSUE THREAD

**Issue by Pzy-ss** [VITA-Group/EnlightenGAN#92]
Your EnlightenGAN is enlightening and the source code is also elegant! But the variable _opt.patchD_3_ makes me confused. What does it mean? It seems that multiple patches instead of one are taken into consideration only if _opt.patchD_3_ larger than 0. Could you please give a simple explanation about the variable? Appreciate!

**Comment by yueruchen** [comment]
It is designed to set the local discriminator. Check here `https://github.com/VITA-Group/EnlightenGAN/blob/d7500af765a11944c2bdb0ca40ffcfcf76c7928e/models/single_model.py#L214`
