### ISSUE TITLE
Some questions on debug

### ISSUE THREAD

**Issue by yuyudiandian** [VITA-Group/EnlightenGAN#98]
When I debug predict.py ,running to this step(line 26) , the code gets stuck directly at this step. But I click run button, code will run without any question.
![image](https://user-images.githubusercontent.com/71555221/128354440-da1951be-3043-4399-ac30-d79b2e9b71ed.png)

**Comment by yueruchen** [comment]
I can not help if you do not print the error log

**Comment by yuyudiandian** [comment]
Thank you for your response! I have already solved it!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yifan ***@***.***&gt;; 
发送时间: 2021年8月23日(星期一) 上午9:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [VITA-Group/EnlightenGAN] Some questions on debug (#98)





 
I can not help if you do not print the error log
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yueruchen** [comment]
Great!
