### ISSUE TITLE
Problems about trainig on custom datasets

### ISSUE THREAD

**Issue by Spicy-curry** [VITA-Group/EnlightenGAN#99]
When i train enlightengan on other datasets(sid datasets to rgb),i meet a problem below.
pictures are 4256*2848,i'm using an 3090 gpu.Would you please help me?
<img width="470" alt="1" src="https://user-images.githubusercontent.com/54784700/130235095-560c867a-ab35-4bfd-ad97-13e44693bf43.png">

**Comment by yueruchen** [comment]
Directly replace the original data with yours should not occur any bugs

**Comment by Spicy-curry** [comment]
Thank you for your reply,i changed num_workers to 0,and there was no problem
